trustbloc/agent-sdk

- .github/workflows/build.yml
> fix: Fixes github actions

- ci/azure-pipelines.yml
> ci: JS publish npm package

- cmd/agent-js-worker/main.go
- cmd/agent-js-worker/src/agent.js
- pkg/controller/command/didclient/command.go
- pkg/controller/command/didclient/command_test.go
- pkg/controller/command/didclient/models.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
> feat: create peer DID command in didclient

- cmd/agent-js-worker/src/agent.js
- pkg/controller/command/didclient/command.go
- pkg/controller/command/didclient/command_test.go
> chore: renaming createBlocDID to createTrustBlocDID

- Makefile
- ci/azure-pipelines.yml
> ci: Fixes docker publish job

- cmd/agent-js-worker/src/agent.js
- pkg/controller/command/didclient/command.go
> fix: typo in create trustbloc did command name

- cmd/agent-js-worker/main.go
- cmd/agent-rest/startcmd/start.go
Keeps resolvers initial order. The tests were failing due to unpredictable order.
In this PR we track initial order.
> fix: Keeps resolvers initial order

- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-mobile/pkg/api/api.go
- cmd/agent-mobile/pkg/api/didclient.go
- cmd/agent-mobile/pkg/wrappers/command/aries.go
- cmd/agent-mobile/pkg/wrappers/command/didclient.go
- cmd/agent-mobile/pkg/wrappers/command/didclient_test.go
- cmd/agent-mobile/pkg/wrappers/rest/aries.go
- pkg/controller/command/didclient/command.go
- pkg/controller/command/util.go
- pkg/controller/command/util_test.go
Adds the possibility to create Trustbloc/Peer DIDs.
NOTE: REST usage is not supported yet.
Part of #24 
> feat: Adds the possibility to create Trustbloc/Peer DIDs

- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- go.mod
- go.sum
- pkg/controller/command/didclient/command.go
- pkg/controller/command/didclient/models.go
Update sidetree, did-method
Closes #30
Signed-off-by: Sandra Vrtikapa <sandra.vrtikapa@securekey.com>
> chore: update sidetree, did-method

- cmd/agent-mobile/pkg/wrappers/rest/aries.go
- cmd/agent-mobile/pkg/wrappers/rest/didclient.go
- cmd/agent-mobile/pkg/wrappers/rest/didclient_test.go
- cmd/agent-mobile/pkg/wrappers/rest/endpoints.go
- cmd/agent-mobile/pkg/wrappers/rest/kms.go
Adds the possibility to create Trustbloc/Peer DIDs (mobile rest)
Closes #24 
> feat: Adds the possibility to create Trustbloc/Peer DIDs (mobile rest)

- cmd/agent-mobile/pkg/wrappers/command/didclient.go
- cmd/agent-mobile/pkg/wrappers/command/didclient_test.go
- cmd/agent-mobile/pkg/wrappers/rest/didclient.go
- cmd/agent-mobile/pkg/wrappers/rest/endpoints.go
- pkg/controller/command/didclient/command.go
- pkg/controller/command/didclient/command_test.go
> refactor: Replaces Bloc with TrustBloc

- cmd/agent-js-worker/package-lock.json
- cmd/agent-js-worker/package.json
- cmd/agent-js-worker/rest.js
- cmd/agent-js-worker/src/agent-rest-client.js
- cmd/agent-js-worker/src/worker-impl-rest.js
- cmd/agent-js-worker/src/worker-loader-rest.js
- cmd/agent-js-worker/webpack.config.rest.js
REST SDK support for js. The code was mainly copied from Aries.
> feat: REST SDK support for js.

- cmd/agent-js-worker/src/agent-rest-client.js
> feat: DIDClient REST support (JS)

- cmd/agent-js-worker/src/agent-rest-client.js
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-mobile/pkg/api/api.go
- cmd/agent-mobile/pkg/api/credentialclient.go
- cmd/agent-mobile/pkg/api/presentationclient.go
- cmd/agent-mobile/pkg/wrappers/command/aries.go
- cmd/agent-mobile/pkg/wrappers/command/credentialclient.go
- cmd/agent-mobile/pkg/wrappers/command/credentialclient_test.go
- cmd/agent-mobile/pkg/wrappers/command/presentationclient.go
- cmd/agent-mobile/pkg/wrappers/command/presentationclient_test.go
- cmd/agent-mobile/pkg/wrappers/rest/aries.go
- cmd/agent-mobile/pkg/wrappers/rest/credentialclient.go
- cmd/agent-mobile/pkg/wrappers/rest/credentialclient_test.go
- cmd/agent-mobile/pkg/wrappers/rest/endpoints.go
- cmd/agent-mobile/pkg/wrappers/rest/presentationclient.go
- cmd/agent-mobile/pkg/wrappers/rest/presentationclient_test.go
- pkg/controller/command/credentialclient/command.go
- pkg/controller/command/presentationclient/command.go
- pkg/controller/controller.go
- pkg/controller/rest/credentialclient/operation.go
- pkg/controller/rest/credentialclient/operation_test.go
- pkg/controller/rest/presentationclient/operation.go
- pkg/controller/rest/presentationclient/operation_test.go
Adds Credential/Presentation clients support (for all targets).
> feat: Credential/Presentation clients support

- cmd/agent-mobile/README.md
- cmd/agent-mobile/doc/project_structure.md
Adds mobile docs. Documentation was mainly copied from Aries.
> docs: Adds mobile docs

- .gitignore
- Makefile
- cmd/agent-rest/main.go
- cmd/agent-rest/startcmd/start.go
- cmd/agent-rest/startcmd/start_test.go
- deployments/agent-rest/.env
- deployments/agent-rest/docker-compose.yml
- deployments/demo/openapi/.env
- deployments/demo/openapi/docker-compose.yml
- deployments/sidetree-mock/.env
- deployments/sidetree-mock/docker-compose.yml
- pkg/controller/rest/didclient/models.go
- pkg/controller/rest/didclient/operation.go
- pkg/controller/rest/rest.go
- scripts/generate-openapi-demo-specs.sh
- scripts/generate-openapi-spec.sh
- scripts/generate_test_keys.sh
- scripts/run-openapi-demo.sh
> feat: Adds OpenAPI spec

- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- go.mod
- go.sum
> chore: update trustbloc-did-method

- cmd/agent-js-worker/src/agent-rest-client.js
- cmd/agent-js-worker/src/agent.js
- pkg/controller/command/errors.go
- pkg/controller/command/mediatorclient/command.go
- pkg/controller/command/mediatorclient/command_test.go
- pkg/controller/command/mediatorclient/models.go
- pkg/controller/controller.go
- pkg/controller/internal/mocks/protocol/didexchange.go
- pkg/controller/internal/mocks/protocol/outofband.go
- pkg/controller/internal/testutil/testutil.go
- pkg/controller/rest/mediatorclient/models.go
- pkg/controller/rest/mediatorclient/operation.go
- pkg/controller/rest/mediatorclient/operation_test.go
- added REST, JS bindings
TODO: mobile binding
- Part of #57
> feat: mediatorclient command controller with connect command

- Makefile
- ci/azure-pipelines.yml
- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-js-worker/src/agent.js
- scripts/aries_bdd_tests.sh
- scripts/aries_js_bdd_tests.sh
> test: Adds JS bdd tests based on Aries

- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- go.mod
- go.sum
> chore: update trustbloc-did-method revision

- ci/azure-pipelines.yml
> ci: Adds dependencies for Publish job

- cmd/agent-mobile/pkg/wrappers/storage/storage.go
> fix: Maps custom error to storage error (mobile)

- cmd/agent-rest/startcmd/start.go
- pkg/controller/command/mediatorclient/command.go
- pkg/controller/command/mediatorclient/command_test.go
- pkg/controller/command/mediatorclient/models.go
- pkg/controller/controller.go
- pkg/controller/internal/msghandler/messagesvc.go
- pkg/controller/internal/msghandler/notifier.go
- pkg/controller/rest/mediatorclient/operation.go
- pkg/controller/rest/mediatorclient/operation_test.go
> feat: state complete message check for mediator connect

- cmd/agent-js-worker/README.md
Adds documentation for agent (js usage).
> docs: Adds documentation for agent js

- cmd/agent-js-worker/src/agent-rest-client.js
- cmd/agent-js-worker/src/agent.js
- pkg/controller/command/mediatorclient/command.go
- pkg/controller/command/mediatorclient/command_test.go
- pkg/controller/command/mediatorclient/models.go
- pkg/controller/command/registry.go
- pkg/controller/command/registry_test.go
- pkg/controller/controller.go
- pkg/controller/internal/mocks/protocol/outofband.go
- pkg/controller/rest/mediatorclient/models.go
- pkg/controller/rest/mediatorclient/operation.go
- pkg/controller/rest/mediatorclient/operation_test.go
> feat: mediator reconnect all & create invitation

- Makefile
- README.md
- docs/test/build.md
Adds links to the README (bindings).
> docs: Adds links to the README (bindings)

- cmd/agent-js-worker/src/agent-rest-client.js
- cmd/agent-js-worker/src/agent.js
- pkg/controller/command/blindedrouting/command.go
- pkg/controller/command/blindedrouting/command_test.go
- pkg/controller/command/blindedrouting/models.go
- pkg/controller/command/mediatorclient/command.go
- pkg/controller/command/mediatorclient/command_test.go
- pkg/controller/command/mediatorclient/models.go
- pkg/controller/controller.go
- pkg/controller/internal/mocks/protocol/provider.go
- pkg/controller/rest/blindedrouting/models.go
- pkg/controller/rest/blindedrouting/operation.go
- pkg/controller/rest/blindedrouting/operation_test.go
- pkg/controller/rest/mediatorclient/operation.go
- pkg/controller/rest/mediatorclient/operation_test.go
- added send diddoc request command
- added send register route request command
- added JS & REST bindings
- closes #74
> feat: blinded routing command features

- cmd/agent-js-worker/main.go
- cmd/agent-js-worker/src/agent.js
> fix: agent-sdk JS integration issues

- cmd/agent-js-worker/main.go
> fix: Revert echoTimeout change

- cmd/agent-js-worker/main.go
> feat: add support for remoteKMS/Crypto

- cmd/agent-js-worker/main.go
- pkg/auth/zcapld/service.go
- pkg/auth/zcapld/service_test.go
> feat: Support to pass userHalfSecret and sub in header to authz kms

- cmd/agent-js-worker/main.go
this change includes the option to run KMS/Crypto services
either locally (via indexDB) or remotely on a key server
closes #67
> feat: complete remoteKMS/remoteCrypto in agent-js-worker

- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-js-worker/main.go
- go.mod
- go.sum
- pkg/storage/jsindexeddbcache/db.go
- pkg/storage/jsindexeddbcache/db_test.go
- scripts/check_unit_wasm.sh
> feat: add edv caching

- pkg/storage/jsindexeddbcache/db.go
- pkg/storage/jsindexeddbcache/db_test.go
> fix: remove clear cache when open store

- pkg/storage/jsindexeddbcache/db.go
> fix:  remove clear cache when open store

- cmd/agent-js-worker/main.go
> refactor: replace useRemoteKMS with KMSType in agent options

- pkg/storage/jsindexeddbcache/db.go
- pkg/storage/jsindexeddbcache/db_test.go
> feat: Clear jsindexeddbcache when user close browser

- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
> chore: update hub-kms dependency

- cmd/agent-mobile/pkg/wrappers/command/aries.go
> fix: Adds missing message handler and notifier

- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- go.mod
- go.sum
with remoteCryptoBox for legacyPacker
> chore: update latest aries-framework-go

- cmd/agent-js-worker/src/agent.js
- pkg/controller/command/errors.go
- pkg/controller/command/store/command.go
- pkg/controller/command/store/command_test.go
- pkg/controller/command/store/models.go
- pkg/controller/controller.go
- pkg/controller/internal/mocks/mock_store.go
- pkg/controller/internal/mocks/protocol/provider.go
- pkg/controller/rest/blindedrouting/operation_test.go
> feat: Exposes store to be accessible through the wasm

- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-js-worker/main.go
- cmd/agent-js-worker/src/agent.js
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- go.mod
- go.sum
- pkg/controller/command/store/command.go
- pkg/controller/command/store/command_test.go
- pkg/controller/internal/mocks/mock_store.go
> feat: add flush store

- pkg/storage/jsindexeddbcache/db.go
- pkg/storage/jsindexeddbcache/db_test.go
> fix: cache iterator bug

- pkg/controller/command/store/command.go
> fix: flush command

- Makefile
- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-js-worker/main.go
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- go.mod
- go.sum
> chore: update aries revision

- Makefile
- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- go.mod
- go.sum
Updated aries-framework-go brings improved EDV REST provider performance.
> feat: Update aries-framework-go version

- cmd/agent-js-worker/README.md
Adds all possible values for JS agent.
> docs: Adds all possible values for JS agent

- ci/version_var.sh
> chore: Complete release 0.1.5

- ci/azure-pipelines.yml
- ci/version_var.sh
> chore: Agent SDK v0.1.5 release

- ci/version_var.sh
> chore: bump version to 0.1.6

- pkg/controller/command/mediatorclient/command.go
- pkg/controller/command/mediatorclient/command_test.go
- pkg/controller/command/mediatorclient/models.go
- pkg/controller/rest/mediatorclient/operation_test.go
> fix: performance enhancement in mediatorclient didconnect

- cmd/agent-js-worker/main.go
> chore: Support Aries log level configuration

- pkg/controller/command/mediatorclient/command.go
> fix: mediator client connect timeout issue

- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- go.mod
- go.sum
> chore: Update aries dependency and remove the forks

- cmd/agent-js-worker/src/agent.js
> fix: 'req' undefined issue in blinded routing command

- Makefile
- ci/azure-pipelines.yml
- ci/version_var.sh
- deployments/agent-rest/.env
- deployments/sidetree-mock/.env
- docs/rest/agent_docker.md
- images/agent-rest/Dockerfile
- scripts/aries_bdd_tests.sh
- scripts/aries_js_bdd_tests.sh
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
> ci: migrate to ghcr

- README.md
- ci/azure-pipelines.yml
- docs/rest/openapi_demo.md
- scripts/aries_bdd_tests.sh
- scripts/aries_js_bdd_tests.sh
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
> chore: rename master branch to main

- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- go.mod
- go.sum
* fix serialization of did.Service (hyperledger/aries-framework-go#2498)
> chore: update aries-framework-go

- Makefile
- cmd/agent-mobile/pkg/wrappers/command/mediatorclient_test.go
- cmd/agent-mobile/pkg/wrappers/command/outofband_test.go
- cmd/agent-mobile/pkg/wrappers/rest/mediatorclient_test.go
- cmd/agent-mobile/pkg/wrappers/rest/outofband_test.go
- docs/rest/openapi_demo.md
- pkg/controller/command/mediatorclient/command_test.go
- pkg/controller/rest/mediatorclient/operation_test.go
and replaced oob-invitation with out-of-band in the @type uri
> chore: update makefile with latest AFG

- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- go.mod
- go.sum
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
> chore: update aries-framework-go revision

- Makefile
- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- go.mod
- go.sum
> chore: upgrade afg, kms and edge-core

- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- go.mod
- go.sum
includes derive credential fixes
> chore: updated aries framework go version

- cmd/agent-js-worker/main.go
> chore: use aries did key resolver

- ci/version_var.sh
> chore: Bump version to 0.1.7

- Makefile
- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- go.mod
- go.sum
* /verifiable/presentation/generate: preload presentation-exchange JSONLD context: hyperledger/aries-framework-go#2634
> chore: update AFGO

- pkg/controller/command/didclient/command.go
- pkg/controller/command/didclient/command_test.go
> fix: return discoverable did trustbloc

- Makefile
- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-js-worker/package-lock.json
- cmd/agent-js-worker/src/agent-rest-client.js
- cmd/agent-js-worker/src/agent.js
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-mobile/pkg/api/introduce.go
- cmd/agent-mobile/pkg/api/mediator.go
- cmd/agent-mobile/pkg/api/outofband.go
- cmd/agent-mobile/pkg/wrappers/command/introduce.go
- cmd/agent-mobile/pkg/wrappers/command/introduce_test.go
- cmd/agent-mobile/pkg/wrappers/command/outofband.go
- cmd/agent-mobile/pkg/wrappers/command/outofband_test.go
- cmd/agent-mobile/pkg/wrappers/rest/endpoints.go
- cmd/agent-mobile/pkg/wrappers/rest/introduce.go
- cmd/agent-mobile/pkg/wrappers/rest/introduce_test.go
- cmd/agent-mobile/pkg/wrappers/rest/mediator.go
- cmd/agent-mobile/pkg/wrappers/rest/outofband.go
- cmd/agent-mobile/pkg/wrappers/rest/outofband_test.go
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- go.mod
- go.sum
- pkg/controller/command/mediatorclient/command.go
- pkg/controller/internal/mocks/protocol/outofband.go
Pulling in https://github.com/hyperledger/aries-framework-go/commit/a0e436ad8e8108d7a35c55e152a85e00d43e5b1f (from PR https://github.com/hyperledger/aries-framework-go/pull/2657)
> chore: update AFGO - delete outofband.Request

- pkg/controller/command/didclient/command.go
- pkg/controller/command/didclient/command_test.go
> fix: "CreatePeerDID" command

- pkg/controller/command/didclient/command.go
- pkg/controller/command/didclient/command_test.go
> fix: create did discoverable did

- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/main.go
> feat: switch to custom JSON-LD document loader with network support

- cmd/agent-rest/go.mod
- cmd/agent-rest/startcmd/start.go
- cmd/agent-rest/startcmd/start_test.go
> feat: use custom document loader with network support for server sdk

- go.mod
- pkg/controller/command/store/command.go
- pkg/controller/command/store/command_test.go
> fix: indexedDB.Query() panic when pageSize < 1

- cmd/wallet-js-sdk/.gitignore
- cmd/wallet-js-sdk/README.md
- cmd/wallet-js-sdk/package-lock.json
- cmd/wallet-js-sdk/package.json
- cmd/wallet-js-sdk/src/index.js
- cmd/wallet-js-sdk/webpack.common.js
- cmd/wallet-js-sdk/webpack.dev.js
- cmd/wallet-js-sdk/webpack.prod.js
> feat: initial scaffolding for wallet JS SDK

- cmd/wallet-js-sdk/package-lock.json
- cmd/wallet-js-sdk/package.json
- cmd/wallet-js-sdk/src/device/login.js
- cmd/wallet-js-sdk/src/device/register.js
- cmd/wallet-js-sdk/src/didcomm/connect.js
- cmd/wallet-js-sdk/src/index.js
- cmd/wallet-js-sdk/src/universal/vc-wallet.js
- cmd/wallet-js-sdk/src/util/event.js
- added universal wallet JS API
- added didcommm connect
- added device registration
- added basic event utils
Part of #209
> feat: wallet SDK APIS

- cmd/agent-js-worker/main.go
- pkg/controller/command/didclient/command.go
- pkg/controller/command/didclient/command_test.go
- pkg/controller/controller.go
- pkg/controller/rest/didclient/operation.go
> chore: add sidetree request token

- cmd/wallet-js-sdk/.gitignore
- cmd/wallet-js-sdk/README.md
- cmd/wallet-js-sdk/karma.conf.js
- cmd/wallet-js-sdk/package-lock.json
- cmd/wallet-js-sdk/package.json
- cmd/wallet-js-sdk/scripts/generate_test_keys.sh
- cmd/wallet-js-sdk/scripts/setup_agent_assets.sh
- cmd/wallet-js-sdk/scripts/setup_test.sh
- cmd/wallet-js-sdk/src/didcomm/connect.js
- cmd/wallet-js-sdk/src/index.js
- cmd/wallet-js-sdk/src/util/event.js
- cmd/wallet-js-sdk/test/fixtures/.env
- cmd/wallet-js-sdk/test/fixtures/docker-compose.yml
- cmd/wallet-js-sdk/test/specs/common.js
- cmd/wallet-js-sdk/test/specs/didcomm/connect.spec.js
- added test framewor based on karma, mocha, chai & webpack
- added tests for did connect and mediator features
- closes #214
> feat: test framework for wallet-sdk

- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/main.go
> chore: enable remote fetching for JSON-LD contexts (temp solution)

- Makefile
- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-js-worker/src/agent-rest-client.js
- cmd/agent-js-worker/src/agent.js
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- cmd/wallet-js-sdk/package-lock.json
- cmd/wallet-js-sdk/package.json
- cmd/wallet-js-sdk/scripts/setup_test.sh
- cmd/wallet-js-sdk/src/didcomm/connect.js
- cmd/wallet-js-sdk/src/index.js
- cmd/wallet-js-sdk/src/universal/vc-wallet.js
- cmd/wallet-js-sdk/test/fixtures/.env
- cmd/wallet-js-sdk/test/fixtures/config.ini
- cmd/wallet-js-sdk/test/fixtures/docker-compose.yml
- cmd/wallet-js-sdk/test/specs/common.js
- cmd/wallet-js-sdk/test/specs/didcomm/connect.spec.js
- cmd/wallet-js-sdk/test/specs/didmanager/didmanager.spec.js
- cmd/wallet-js-sdk/test/specs/universal/vcwallet.spec.js
- go.mod
- go.sum
- pkg/controller/command/didclient/command.go
- pkg/controller/command/didclient/command_test.go
- pkg/controller/rest/didclient/models.go
- added DID manager in wallet SDK for
- Creating TrustBloc DIDs.
- Creating Peer DIDs.
- Saving Custom DIDs along with keys.
- Getting all Saved DIDs.
- added tests for DID manager and universal wallet
- closes #218
- part of #209
> feat: DID manger in wallet SDK

- cmd/wallet-js-sdk/.gitignore
- cmd/wallet-js-sdk/README.md
- cmd/wallet-js-sdk/scripts/generate_test_keys.sh
- cmd/wallet-js-sdk/src/did/didmanager.js
- cmd/wallet-js-sdk/src/index.js
- cmd/wallet-js-sdk/src/user/walletUser.js
- cmd/wallet-js-sdk/test/specs/didmanager/didmanager.spec.js
- cmd/wallet-js-sdk/test/specs/user/walletUser.spec.js
> feat: wallet user APIs

- cmd/wallet-js-sdk/src/credential/credential-manager.js
- cmd/wallet-js-sdk/src/universal/vc-wallet.js
- cmd/wallet-js-sdk/test/specs/credential/credential-manager.spec.js
> feat: wallet JS SDK - Credential queries

- cmd/agent-js-worker/package-lock.json
- docs/test/build.md
Signed-off-by: talwinder kaur <talwinder.kaur@securekey.com>
> chore: update npm 7 and update doc

- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-js-worker/main.go
- cmd/agent-js-worker/src/agent-rest-client.js
- cmd/agent-js-worker/src/agent.js
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- cmd/wallet-js-sdk/src/index.js
- cmd/wallet-js-sdk/src/universal/vc-wallet.js
- cmd/wallet-js-sdk/src/user/wallet-user.js
- cmd/wallet-js-sdk/test/specs/user/wallet-user.spec.js
- go.mod
- go.sum
- added `profileExists()` command
- added more options to unlock wallet features using EDV & WebKMS
including ZCAP-LD features
- Part of #209
> feat: universal wallet integration issue fixes

- cmd/wallet-js-sdk/src/credential/credential-manager.js
- cmd/wallet-js-sdk/src/did/didmanager.js
- cmd/wallet-js-sdk/src/index.js
- cmd/wallet-js-sdk/src/universal/vc-wallet.js
- cmd/wallet-js-sdk/test/specs/credential/credential-manager.spec.js
- cmd/wallet-js-sdk/test/specs/didmanager/didmanager.spec.js
- cmd/wallet-js-sdk/test/specs/universal/vcwallet.spec.js
- pkg/controller/command/didclient/command.go
- support for multiple credential save
- support for multiple credential save from presentation
- performance enhancement
- get did by ID feature
- fix for P-256 & P-384 orb DID creation
- part of #209
> feat: wallet sdk updates

- cmd/wallet-js-sdk/src/didcomm/blinded.js
- cmd/wallet-js-sdk/src/universal/vc-wallet.js
- fixes for issues found during sandbox blinded routing testsing
- Part of #209
> chore: fixes in blinded routing

- cmd/agent-js-worker/src/agent-rest-client.js
- cmd/agent-js-worker/src/agent.js
- cmd/agent-mobile/pkg/api/didclient.go
- cmd/agent-mobile/pkg/wrappers/command/didclient.go
- cmd/agent-mobile/pkg/wrappers/command/didclient_test.go
- cmd/agent-mobile/pkg/wrappers/rest/didclient.go
- cmd/agent-mobile/pkg/wrappers/rest/didclient_test.go
- cmd/agent-mobile/pkg/wrappers/rest/endpoints.go
- cmd/wallet-js-sdk/docs/wallet_sdk.md
- cmd/wallet-js-sdk/src/did/didmanager.js
- cmd/wallet-js-sdk/test/specs/credential/credential-manager.spec.js
- cmd/wallet-js-sdk/test/specs/didmanager/didmanager.spec.js
- pkg/controller/command/didclient/command.go
- pkg/controller/command/didclient/command_test.go
- pkg/controller/command/didclient/models.go
- pkg/controller/rest/didclient/models.go
- pkg/controller/rest/didclient/operation.go
> chore: Rename Bloc DID APIs to Orb DID

- cmd/wallet-js-sdk/docs/wallet_sdk.md
- cmd/wallet-js-sdk/package.json
- cmd/wallet-js-sdk/src/did/didmanager.js
- cmd/wallet-js-sdk/src/didcomm/didcomm.js
- cmd/wallet-js-sdk/src/universal/vc-wallet.js
- cmd/wallet-js-sdk/test/specs/mocks/adapters.js
> fix: web wallet WACI integration issues

- cmd/wallet-js-sdk/src/didcomm/didcomm.js
> chore: enable loggin for WACI flow

- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/main.go
> feat: Support for json-ld context without start-up context loader

- cmd/wallet-js-sdk/docs/wallet_sdk.md
- cmd/wallet-js-sdk/src/didcomm/didcomm.js
- cmd/wallet-js-sdk/test/specs/didcomm/didcomm.spec.js
- added wait for presentation sent state update for wallet WACI flow
> feat: wallet present proof wait for state update option

- cmd/agent-js-worker/main.go
Performance problems in the previous implementation were caused by using a default storage provider that in the case of `Wallet` is EDV. This PR switches to indexedDB while supporting remote JSON-LD context providers.
> perf: improvements for JSON-LD loader with remote providers support

- cmd/agent-js-worker/main.go
> feat: enable remote loader if no context providers specified

- Makefile
- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- go.mod
- go.sum
> chore: update latest afgo fix with verifiable cmd

- ci/version_var.sh
> chore: release 0.1.7

- cmd/wallet-js-sdk/docs/wallet_sdk.md
- cmd/wallet-js-sdk/src/didcomm/didcomm.js
- cmd/wallet-js-sdk/test/specs/didcomm/didcomm.spec.js
- cmd/wallet-js-sdk/test/specs/mocks/adapters.js
> feat: handling problem reports for WACI

- cmd/agent-js-worker/src/agent-rest-client.js
- cmd/agent-js-worker/src/agent.js
- cmd/agent-mobile/pkg/api/didclient.go
- cmd/agent-mobile/pkg/wrappers/command/blindedrouting.go
- cmd/agent-mobile/pkg/wrappers/command/didclient.go
- cmd/agent-mobile/pkg/wrappers/command/didclient_test.go
- cmd/agent-mobile/pkg/wrappers/command/mediatorclient.go
- cmd/agent-mobile/pkg/wrappers/rest/didclient.go
- cmd/agent-mobile/pkg/wrappers/rest/didclient_test.go
- cmd/agent-mobile/pkg/wrappers/rest/endpoints.go
- cmd/agent-mobile/pkg/wrappers/rest/mediatorclient.go
- cmd/wallet-js-sdk/docs/wallet_sdk.md
- cmd/wallet-js-sdk/src/did/didmanager.js
- cmd/wallet-js-sdk/test/specs/credential/credential-manager.spec.js
- cmd/wallet-js-sdk/test/specs/didcomm/didcomm.spec.js
- cmd/wallet-js-sdk/test/specs/didmanager/didmanager.spec.js
- cmd/wallet-js-sdk/test/specs/mocks/adapters.js
- pkg/controller/command/didclient/command.go
- pkg/controller/command/didclient/command_test.go
- pkg/controller/command/didclient/models.go
- pkg/controller/rest/didclient/models.go
- pkg/controller/rest/didclient/operation.go
> feat: add orb did resolve method

- cmd/wallet-js-sdk/test/specs/credential/credential-manager.spec.js
- cmd/wallet-js-sdk/test/specs/didmanager/didmanager.spec.js
- pkg/controller/command/didclient/command.go
> feat: remove retry in resolve orb did

- cmd/wallet-js-sdk/src/user/wallet-user.js
> feat: use orb anchored DID

- cmd/wallet-js-sdk/src/user/wallet-user.js
> fix: resolve orb did in get preferences

- cmd/wallet-js-sdk/src/user/wallet-user.js
> fix: resolveOrbDID in getPreferences

- cmd/wallet-js-sdk/src/user/wallet-user.js
> fix: log msg

- cmd/wallet-js-sdk/src/user/wallet-user.js
> fix: log msgs

- cmd/agent-js-worker/main.go
> chore: add 1 sec max time for Unanchored

- cmd/agent-js-worker/main.go
Reverts trustbloc/agent-sdk#281
> Revert "chore: add 1 sec max time for Unanchored"

- cmd/agent-js-worker/main.go
- pkg/controller/command/didclient/command.go
- pkg/controller/command/didclient/command_test.go
- pkg/controller/controller.go
- pkg/controller/rest/didclient/operation.go
> fix: UnanchoredDIDMaxLifeTime option

- cmd/wallet-js-sdk/docs/wallet_sdk.md
- cmd/wallet-js-sdk/package-lock.json
- cmd/wallet-js-sdk/package.json
- cmd/wallet-js-sdk/src/did/didmanager.js
- cmd/wallet-js-sdk/src/user/wallet-user.js
- cmd/wallet-js-sdk/src/util/helper.js
- cmd/wallet-js-sdk/test/specs/util/helper.spec.js
- added helper function for normalizing/grouping duplicate presentation
submission results
- added helper function to update presentation submission presentation
based on selections
> feat: normalize presentation submission

- cmd/wallet-js-sdk/src/didcomm/didcomm.js
- cmd/wallet-js-sdk/src/user/wallet-user.js
- cmd/wallet-js-sdk/test/specs/credential/credential-manager.spec.js
- cmd/wallet-js-sdk/test/specs/didcomm/didcomm.spec.js
> feat: normalized credential results in WACI share flow

- cmd/wallet-js-sdk/src/did/didmanager.js
- cmd/wallet-js-sdk/src/user/wallet-user.js
- cmd/wallet-js-sdk/test/specs/didmanager/didmanager.spec.js
> fix: saveDID when we get anchored orb DID

- Makefile
- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-js-worker/main.go
- cmd/agent-js-worker/main_test.go
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- go.mod
- go.sum
Signed-off-by: Andrii Holovko <andriy.holovko@gmail.com>
> chore: update Aries and kms

- pkg/auth/zcapld/service.go
Signed-off-by: Andrii Holovko <andriy.holovko@gmail.com>
> fix: zcap signing and Shamir secret share header

- Makefile
- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-js-worker/src/agent-rest-client.js
- cmd/agent-js-worker/src/agent.js
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- go.mod
- go.sum
> chore: update to latest aries

- cmd/agent-js-worker/src/agent-rest-client.js
- cmd/agent-js-worker/src/agent.js
- cmd/wallet-js-sdk/docs/wallet_sdk.md
- cmd/wallet-js-sdk/src/didcomm/didcomm.js
- cmd/wallet-js-sdk/src/universal/vc-wallet.js
- cmd/wallet-js-sdk/src/user/wallet-user.js
- cmd/wallet-js-sdk/src/util/helper.js
- cmd/wallet-js-sdk/test/fixtures/testdata/cred-fulfillment-DL.json
- cmd/wallet-js-sdk/test/fixtures/testdata/cred-manifest-withdef.json
- cmd/wallet-js-sdk/test/fixtures/testdata/cred-manifest-withoptions.json
- cmd/wallet-js-sdk/test/fixtures/testdata/cred-manifest.json
- cmd/wallet-js-sdk/test/specs/collection/collection-manager.spec.js
- cmd/wallet-js-sdk/test/specs/common.js
- cmd/wallet-js-sdk/test/specs/didcomm/didcomm.spec.js
- cmd/wallet-js-sdk/test/specs/mocks/adapters.js
- added WACI issuance initiate interaction and complete interaction
- added bdd tests for WACI issuance for Presentation Exchange, DID Auth
& Basic flow.
- Closes #290
> feat: WACI issuance in Wallet JS SDK

- Makefile
- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- cmd/wallet-js-sdk/src/collection/collections.js
- cmd/wallet-js-sdk/test/specs/collection/collection-manager.spec.js
- go.mod
- go.sum
- fixes the issue where deleting tagged credential causes `data not
found` error later while using the collection
> fix: deleting credential under a collection

- cmd/wallet-js-sdk/docs/wallet_sdk.md
- cmd/wallet-js-sdk/src/util/helper.js
- cmd/wallet-js-sdk/test/specs/didcomm/didcomm.spec.js
- cmd/wallet-js-sdk/test/specs/mocks/adapters.js
- cmd/wallet-js-sdk/test/specs/util/helper.spec.js
> feat: Wallet JS SDK - adding goal_code helper

- cmd/agent-rest/startcmd/start.go
- cmd/agent-rest/startcmd/start_test.go
> feat: add key type parameters to agent-rest

- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- go.mod
- go.sum
> chore: update to latest orb

- cmd/wallet-js-sdk/src/didcomm/didcomm.js
- cmd/wallet-js-sdk/test/fixtures/testdata/cred-fulfillment-udc-vp.json
- cmd/wallet-js-sdk/test/specs/didcomm/didcomm.spec.js
- cmd/wallet-js-sdk/test/specs/mocks/adapters.js
> fix: WACI complete issuance to expect credential fulfillment

- cmd/wallet-js-sdk/src/user/wallet-user.js
Fixes https://github.com/trustbloc/wallet/issues/1400
Signed-off-by: Anton Biriukov <anton.biriukov@securekey.com>
> feat: added new property in user preferences for welcome message dismissal

- cmd/agent-js-worker/main.go
- cmd/agent-rest/startcmd/start.go
- cmd/agent-rest/startcmd/start_test.go
> feat: media-type-profile parameter for agent-sdk rest and wasm

- cmd/agent-js-worker/src/wasm_exec.js
- cmd/wallet-js-sdk/src/didcomm/didcomm.js
- cmd/wallet-js-sdk/test/specs/didcomm/connect.v2.spec.js
- cmd/wallet-js-sdk/test/specs/didcomm/didcomm.v2.spec.js
- cmd/wallet-js-sdk/test/specs/mocks/adapters.js
> feat: didcomm v2 integration with waci issuance

- cmd/wallet-js-sdk/docs/wallet_sdk.md
- cmd/wallet-js-sdk/src/credential/credential-manager.js
- cmd/wallet-js-sdk/test/fixtures/testdata/cred-fulfillment-DL.json
- cmd/wallet-js-sdk/test/fixtures/testdata/cred-manifest-withdef.json
- cmd/wallet-js-sdk/test/specs/credential/credential-manager.spec.js
- cmd/wallet-js-sdk/test/specs/didcomm/didcomm.v1.spec.js
- cmd/wallet-js-sdk/test/specs/didcomm/didcomm.v2.spec.js
- resolving credential once during save and saving as part of credential
metadata
- Part of #321
> feat: resolving credential while saving

- Makefile
- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-js-worker/src/wasm_exec.js
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- cmd/agent-rest/startcmd/start.go
- go.mod
- go.sum
> chore: update afgo version

- cmd/wallet-js-sdk/test/fixtures/.env
- cmd/wallet-js-sdk/test/fixtures/config.ini
- cmd/wallet-js-sdk/test/fixtures/docker-compose.yml
- cmd/wallet-js-sdk/test/specs/common.js
- cmd/wallet-js-sdk/test/specs/didcomm/connect.v2.spec.js
- cmd/wallet-js-sdk/test/specs/didcomm/didcomm.v2.spec.js
- cmd/wallet-js-sdk/test/specs/mocks/adapters.js
- pkg/controller/command/didclient/command.go
> chore: update wallet-js-sdk tests to use single router instance

- cmd/agent-js-worker/main.go
- cmd/agent-rest/startcmd/start.go
- cmd/agent-rest/startcmd/start_test.go
Signed-off-by: Andrii Holovko <andriy.holovko@gmail.com>
> feat: websocket read limit support

- cmd/wallet-js-sdk/karma.conf.js
- cmd/wallet-js-sdk/package-lock.json
> chore: fix package json version

- ci/version_var.sh
> chore: complete release v0.1.8

- cmd/wallet-js-sdk/docs/wallet_sdk.md
- cmd/wallet-js-sdk/src/collection/collections.js
- cmd/wallet-js-sdk/src/credential/credential-manager.js
- cmd/wallet-js-sdk/src/did/didmanager.js
- cmd/wallet-js-sdk/src/user/wallet-user.js
- cmd/wallet-js-sdk/src/util/helper.js
- cmd/wallet-js-sdk/test/specs/didmanager/didmanager.spec.js
- saving unanchored DID after resolve retry till user preference
refreshes DID once it is published
> feat: Saving unanchored DID while cerating Orb DID

- cmd/wallet-js-sdk/src/did/didmanager.js
> fix: refresh DID - save resolved canonical DID

- cmd/wallet-js-sdk/package-lock.json
- cmd/wallet-js-sdk/package.json
- cmd/wallet-js-sdk/src/gnap/client.js
- cmd/wallet-js-sdk/src/index.js
- cmd/wallet-js-sdk/test/specs/gnap/gnap.spec.js
Part of #340
Signed-off-by: Anton Biriukov <anton.biriukov@securekey.com>
> feat: base implementation for GNAP client in wallet-js-sdk

- Makefile
- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- go.mod
- go.sum
Signed-off-by: Volodymyr Kubiv <volodymyr.kubiv@euristiq.com>
> chore: update to latest afgo.

- cmd/wallet-js-sdk/src/gnap/client.js
- cmd/wallet-js-sdk/test/specs/gnap/gnap.spec.js
> feat: pass GNAP continue-token value to gnap client.continue()

- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- go.mod
- go.sum
> chore: updated afgo to latest

- cmd/agent-js-worker/main.go
Signed-off-by: Andrii Holovko <andriy.holovko@gmail.com>
> fix: update bootstrap url

- cmd/agent-js-worker/main.go
> feat: initialize webkms for existing user

- cmd/wallet-js-sdk/src/digest/digest.js
- cmd/wallet-js-sdk/src/gnap/client.js
- cmd/wallet-js-sdk/src/httpsig/signer.js
- cmd/wallet-js-sdk/src/index.js
- cmd/wallet-js-sdk/src/util/helper.js
- cmd/wallet-js-sdk/test/specs/digest/digest.spec.js
- cmd/wallet-js-sdk/test/specs/gnap/gnap.spec.js
- cmd/wallet-js-sdk/test/specs/util/helper.spec.js
Fixes #348 
Manually tested the auth flow with signature verification on - auth was able to verify the signature from wallet successfully:
Unit tests will be added in a follow-up PR, filed https://github.com/trustbloc/agent-sdk/issues/386 for it
> feat: http signature module implementation

- cmd/agent-js-worker/main.go
> feat: wasm vcwallet uses httpsig on gnap-authed webkms requests

- cmd/agent-js-worker/main.go
> feat: enable edv gnap auth in wasm vcwallet handler

- cmd/agent-js-worker/main.go
> fix: add missing gnap header func (with httpsig) for edv call

- Makefile
- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-mobile/pkg/wrappers/command/vcwallet.go
- cmd/agent-mobile/pkg/wrappers/rest/endpoints.go
- cmd/agent-mobile/pkg/wrappers/rest/vcwallet.go
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- go.mod
- go.sum
Signed-off-by: Volodymyr Kubiv <volodymyr.kubiv@euristiq.com>
> chore: update afgo version.

- cmd/wallet-js-sdk/test/fixtures/.env
Signed-off-by: heidihan0000 <daeun.han@avast.com>
> chore: update mediator

- cmd/agent-js-worker/package-lock.json
- cmd/agent-js-worker/package.json
> chore: upgraded axios to resolve security vulnerability

- cmd/agent-js-worker/src/agent.js
- cmd/wallet-js-sdk/test/specs/collection/collection-manager.spec.js
- cmd/wallet-js-sdk/test/specs/common.js
- cmd/wallet-js-sdk/test/specs/credential/credential-manager.spec.js
- cmd/wallet-js-sdk/test/specs/didcomm/connect.v1.spec.js
- cmd/wallet-js-sdk/test/specs/didcomm/connect.v2.spec.js
- cmd/wallet-js-sdk/test/specs/didcomm/didcomm.v1.spec.js
- cmd/wallet-js-sdk/test/specs/didcomm/didcomm.v2.spec.js
- cmd/wallet-js-sdk/test/specs/didmanager/didmanager.spec.js
- cmd/wallet-js-sdk/test/specs/mocks/adapters.js
- cmd/wallet-js-sdk/test/specs/universal/didcommwallet.spec.js
- cmd/wallet-js-sdk/test/specs/universal/vcwallet.spec.js
- cmd/wallet-js-sdk/test/specs/user/wallet-user.spec.js
- cmd/wallet-js-sdk/test/specs/util/helper.spec.js
- scripts/aries_js_bdd_tests.sh
> refactor: build vcwallet  in wasm by default

- cmd/agent-js-worker/vcwallet/main.go
- pkg/controller/command/didclient/command.go
- pkg/controller/command/didclient/command_test.go
- pkg/controller/controller.go
- pkg/controller/rest/didclient/operation.go
closes #406 
Signed-off-by: Rolson Quadras <rolson.quadras@avast.com>
> fix: VC Wallet - add didClient/Store cmd and GNAP headerfunc to KMS/EDV

- cmd/agent-js-worker/vcwallet/main.go
- pkg/agentsetup/setup.go
Fixed an issue where the lite wallet was ignoring the EDV option and wasn't persisting any data outside of IndexedDB.
Also removed some redundant functions I discovered relating to EDV provider creation.
> fix: Lite wallet ignoring EDV option

- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-js-worker/src/agent.js
- cmd/agent-js-worker/vcwallet/go.mod
- cmd/agent-js-worker/vcwallet/go.sum
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- cmd/wallet-js-sdk/docs/wallet_sdk.md
- cmd/wallet-js-sdk/src/credential/credential-manager.js
- cmd/wallet-js-sdk/src/didcomm/didcomm.js
- cmd/wallet-js-sdk/src/universal/vc-wallet.js
- cmd/wallet-js-sdk/test/fixtures/testdata/cred-response-DL.json
- cmd/wallet-js-sdk/test/fixtures/testdata/cred-response-udc-vp.json
- cmd/wallet-js-sdk/test/specs/common.js
- cmd/wallet-js-sdk/test/specs/credential/credential-manager.spec.js
- cmd/wallet-js-sdk/test/specs/didcomm/didcomm.v1.spec.js
- cmd/wallet-js-sdk/test/specs/didcomm/didcomm.v2.spec.js
- cmd/wallet-js-sdk/test/specs/mocks/adapters.js
- cmd/wallet-js-sdk/test/specs/util/helper.spec.js
- go.mod
- go.sum
- pkg/agentsetup/setup.go
To line up with the latest Credential Manifest spec.
Also made some minor updates to KMS interface code due to changes in aries-framework-go.
> feat: Change Credential Fulfillment to Credential Response

- cmd/wallet-js-sdk/docs/wallet_sdk.md
> docs: Update Wallet SDK docs

- cmd/wallet-js-sdk/test/fixtures/docker-compose.yml
> chore: use orb image

- cmd/wallet-js-sdk/src/did/didmanager.js
> fix: checkControllerIsPublished

- Makefile
- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-js-worker/vcwallet/go.mod
- cmd/agent-js-worker/vcwallet/go.sum
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- cmd/wallet-js-sdk/test/specs/universal/vcwallet.spec.js
- go.mod
- go.sum
> test: wallet js sdk jwtvc tests, including pEx v2 

- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-js-worker/src/agent-rest-client.js
- cmd/agent-js-worker/src/agent.js
- cmd/agent-js-worker/src/wasm_exec.js
- cmd/agent-js-worker/vcwallet/go.mod
- cmd/agent-js-worker/vcwallet/go.sum
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-mobile/pkg/api/didclient.go
- cmd/agent-mobile/pkg/wrappers/command/didclient.go
- cmd/agent-mobile/pkg/wrappers/rest/didclient.go
- cmd/agent-mobile/pkg/wrappers/rest/endpoints.go
- cmd/agent-mobile/pkg/wrappers/rest/outofband.go
- cmd/agent-mobile/pkg/wrappers/rest/vdr.go
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- cmd/wallet-js-sdk/src/did/didmanager.js
- cmd/wallet-js-sdk/src/user/wallet-user.js
- go.mod
- go.sum
- pkg/controller/command/didclient/command.go
- pkg/controller/command/didclient/command_test.go
- pkg/controller/command/didclient/models.go
- pkg/controller/rest/didclient/operation.go
> feat: Verify WebDocument From OrbDocument

- .golangci.yml
- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/go.sum
- cmd/agent-js-worker/src/worker-impl-web.js
It fixes call stack issue while initializing agent on web-assembly
Closes [issue](https://github.com/trustbloc/wallet/issues/1876)
> fix: Replace libs with forked one to fix call stack issue on web-assembly

- cmd/wallet-js-sdk/src/credential/credential-manager.js
- cmd/wallet-js-sdk/src/user/wallet-user.js
> feat: support jwtvc

- cmd/agent-js-worker/go.mod
- cmd/agent-js-worker/vcwallet/go.mod
- cmd/agent-js-worker/vcwallet/go.sum
- cmd/agent-mobile/go.mod
- cmd/agent-mobile/go.sum
- cmd/agent-rest/go.mod
- cmd/agent-rest/go.sum
- go.mod
- go.sum
Update json-gold lib version to latest one
Remove forked lib
> chore: update json-gold version to latest

- cmd/wallet-js-sdk/src/oidc/issuance/openid4ci.js
> feat: API stubs for OIDC issuance SDK

- cmd/wallet-js-sdk/src/oidc/presentation/openid4vp.js
- cmd/wallet-js-sdk/test/specs/oidc/presentation/openid4vp.spec.js
Related to #432
- Moved `authToken` parameter to the first place in `initiateOIDCPresentation()` declaration 
- Added more tests for OpenID4VP Initiate API
> test: added more tests for openid4vp initiate api

- cmd/wallet-js-sdk/src/index.js
- cmd/wallet-js-sdk/src/oidc/issuance/openid4ci.js
- cmd/wallet-js-sdk/test/specs/oidc/issuance/oidc4ci.spec.js
> feat: oidc4ci js api

- cmd/wallet-js-sdk/src/oidc/presentation/openid4vp.js
- cmd/wallet-js-sdk/test/fixtures/testdata/openid4vc-mock-did-doc.json
- cmd/wallet-js-sdk/test/fixtures/testdata/openid4vc-mock-presentation-query.json
- cmd/wallet-js-sdk/test/specs/oidc/presentation/openid4vp.spec.js
> test: added unit tests for openid4vp submit api

- cmd/agent-js-worker/src/agent.js
- cmd/wallet-js-sdk/src/index.js
- cmd/wallet-js-sdk/src/jwt/jwtmanager.js
- cmd/wallet-js-sdk/src/universal/vc-wallet.js
- cmd/wallet-js-sdk/test/specs/jwtmanager/jwtmanager.spec.js
> feat: added JS wrappers for JWT sign and verify operations

- cmd/wallet-js-sdk/src/oidc/presentation/openid4vp.js
- cmd/wallet-js-sdk/test/specs/oidc/presentation/openid4vp.spec.js
> feat: integrated JWT signing into openid4vp api

- cmd/wallet-js-sdk/src/oidc/presentation/openid4vp.js
- cmd/wallet-js-sdk/test/specs/oidc/presentation/openid4vp.spec.js
> feat: enabled JWT verification in openid4vp flow

- cmd/wallet-js-sdk/src/oidc/issuance/openid4ci.js
> refactor: refactored jwt signer and added missing params in openid4ci manager
